solution
mate-academy/js_fetch_data_advanced_DOM pull request #36
Opened 2021-04-25 19:15 UTC by Dinexpod

[DEMO LINK](https://Dinexpod.github.io/js_fetch_data_advanced_DOM/)

2021-04-25 19:19 UTC, Dinexpod commented
Привіт, тут взагалі біда) (по коді видно):
- Тести також не запускаються
- async/await не працює
- не розумію де брати ти айді котрі повинні на вхід методам приходити тому просто взяв з минулого завдання
- не розумію самому методи потрібно було визивати чи їх хтось визивати повинен
- ```All IDs and names of phones should be inside of  <li> elements.``` То виходить що в списку повинно бути дві колонки айді та імена?

2021-04-26 11:21 UTC, vpolets requested changes

2021-04-26 11:21 UTC, vpolets commented on src/scripts/main.js
> +}
Promise.race

2021-04-26 11:21 UTC, vpolets commented on src/scripts/main.js
> +}
Promise.allSettled

2021-04-26 13:50 UTC, Dinexpod commented on src/scripts/main.js
> +}
хм, цікаво було))

2021-04-27 11:47 UTC, vpolets approved these changes

2026-05-10 22:12 UTC, closed without merging