solution
mate-academy/js_fetch_data_advanced_DOM pull request #57
Opened 2021-08-18 18:33 UTC by Bohdan996

- [DEMO LINK](https://Bohdan996.github.io/js_fetch_data_advanced_DOM/)

2021-08-20 17:54 UTC, vkryvytskyy requested changes

2021-08-20 17:54 UTC, vkryvytskyy commented on src/scripts/main.js
> +  Promise.all(arr.map(id => phonesDetails(id)))
используй Promise.allSettled

2021-08-20 17:54 UTC, vkryvytskyy commented on src/scripts/main.js
> +    getAllSuccessfulDetails(idArr);
![image](https://user-images.githubusercontent.com/38065883/130274230-6712d00e-a7bb-426c-aaf6-1ae14820e728.png)
А это почему не сделал?

2021-08-21 18:40 UTC, Bohdan996 commented on src/scripts/main.js
> +    getAllSuccessfulDetails(idArr);
Ну здесь написано по желанию и я честно говоря не знаю как это реализовать , я питался через цикл делать и у меня возвращаются одинаковые значения, не думаю, что так должно быть.

2021-08-23 19:00 UTC, vpolets approved these changes

2022-11-28 07:15 UTC, closed without merging